# Generated by Django 4.1.7 on 2023-02-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestbook',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True, verbose_name='Date when deleted'),
        ),
        migrations.AddField(
            model_name='guestbook',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deletion status'),
        ),
        migrations.AlterField(
            model_name='guestbook',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date created at'),
        ),
        migrations.AlterField(
            model_name='guestbook',
            name='desc',
            field=models.TextField(max_length=2000, verbose_name='Entry description'),
        ),
        migrations.AlterField(
            model_name='guestbook',
            name='email',
            field=models.EmailField(max_length=40, verbose_name='Entry email'),
        ),
        migrations.AlterField(
            model_name='guestbook',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Entry name'),
        ),
        migrations.AlterField(
            model_name='guestbook',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('blocked', 'Blocked')], default='active', max_length=10, verbose_name='Status of an entry'),
        ),
        migrations.AlterField(
            model_name='guestbook',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date updated at'),
        ),
    ]
